##mybatis
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.khan.zuul.entity
#  global-config:
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    logic-delete-value: -1
#    logic-not-delete-value: 0
#    #主键类型  auto:"数据库ID自增",input:"用户输入ID", id-worker:"全局唯一ID (数字类型唯一ID)", id-worker-str:"字符串格式的全局唯一ID" uuid:"全局唯一ID UUID";
#    db-config:
#      id-type: auto
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx