server:
  port: 8088

spring:
  application:
    name: zuul
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.211.55.3:3306/khan?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/
security:
  oauth2:
    client:
      client-id: hankai
      client-secret: 123456
      access-token-uri: http://localhost:8089/oauth/token
      user-authorization-uri: http://localhost:8089/oauth/authorize
      scope: user
      resource-ids: user
#      grant-type: password
#      authorized-grant-types: password
    resource:
      token-info-uri: http://localhost:8089/oauth/check_token
      id: user

zuul:
  routes:
    api: /api/**
    auth: /auth/**

